FROM python:3.13-slim

WORKDIR /app
COPY ./backend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY ./backend/app /app

CMD ["celery", "-A", "workers.celery", "worker", "--loglevel=info"]