FROM docker:29-cli

RUN apk add --no-cache \
    bash \
    git \
    curl \
    ca-certificates \
    openssl \
    make \
    openssh-client \
    python3 \
    py3-pip 

WORKDIR /workspace/flash-summary

RUN git config --global --add safe.directory /workspace/flash-summary

CMD ["bash"]